[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
fs_permissions = [{ access = "read", path = ".env" }]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
